spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:h2:mem:currencyexchange;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true